name = "rsvp"
compatibility_date = "2026-03-07"
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "rsvp-db"
database_id = "ec6143a3-a7e6-46fb-9735-d49f00fe425a"
migrations_dir = "migrations"

[vars]
APP_URL = "https://rsvp.bermudatrianglesociety.com"
EMAIL_FROM = "Bermuda Triangle Society <notify@rsvp.bermudatrianglesociety.com>"
AUTH_DOMAIN = "https://maelstrom-auth.cloudflareaccess.com/"

[[routes]]
pattern = "rsvp.bermudatrianglesociety.com"
custom_domain = true
